package br.common;

public enum UpdateArguments {
	RESOLV_FAILED, CONN_INIT, CONN_FAILED, CONN_SUCCESS, GAME_INIT, REDRAW, NOTREACHABLE, ENDTURN, LASER, DOTURN, NOTRIGGERABLE, OUCH, MISS, TOUCHE, CHAT_UPDATE;
}
