package br.controller.net;

public enum EResponse {
	WELCOME, ACCESSDENIED, PLAYERS, SHIP, WRONG, OK, ALLYOURBASE, YOURTURN, TOUCHE, OUCH, MISS, DEATH, AWINNERIS, DRAWGAME, HEYLISTEN, PLAYERSHIP, PLAYERMOVE, PLAYEROUCH;
}
